### ISSUE TITLE
Implement Admin Page

### ISSUE THREAD

**Issue by lcaraang** [warrior-jam/warrior-jam#19] opened 2019-11-21 10:54 UTC
Please do work for this task in a branch named issue-XXX.

Admins can monitor the site for inappropriate content. Ability to create and remove categories of musical skills, genres, events, and users. Admins can view all users and events in Admin tab

**Comment by dmestacio** [comment] 2019-12-18 06:43
Duplicate of issue-7

**Closed as completed by dmestacio** 2019-12-18 06:43 UTC
